# nome da pipeline
name: Run Basic Tests

# em que momento será executada
on: push

jobs:
  # o que vai ser feito nessa pipeline
  # só teremos um job: rodar os testes
  cypress-run:
    # máquina em que será executado
    runs-on: windows-latest

    #passo a passo para rodar os testes
    steps:
      # clone do projeto
      - name: Checkout/Clone do projeto
        uses: actions/checkout@v4

      # exemplo de execução no terminal
      - name: Instalar dependências do projeto
        run: echo Steffi Joji

      # execução e configuração do projeto
      - name: Run testes
        uses: cypress-io/github-action@v6
        with:
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          